In [7]:
import numpy as np
import pandas as pd

In [8]:
ds = pd.read_csv(r"C:\Users\Vijay Kumar Damodar\Internship\Reviews.csv", delimiter = ",")

In [9]:
ds

asin                        name  rating                date  \
0      B0000SX2UC                       Janet       3    October 11, 2005   
1      B0000SX2UC                  Luke Wyatt       1     January 7, 2004   
2      B0000SX2UC                      Brooke       5   December 30, 2003   
3      B0000SX2UC               amy m. teague       3      March 18, 2004   
4      B0000SX2UC               tristazbimmer       4     August 28, 2005   
5      B0000SX2UC                    J. White       4  September 25, 2005   
6      B0000SX2UC  the cell phone store owner       5      April 16, 2004   
7      B0000SX2UC                        Matt       4       April 3, 2004   
8      B0000SX2UC                Charles Cook       5   November 24, 2003   
9      B0000SX2UC             Amazon Customer       3    February 2, 2004   
10     B0000SX2UC                     habblie       4   December 25, 2004   
11     B0000SX2UC            Zachary O. Toups       1   November 29, 2004   
12     B0000SX2UC                        esti       2   September 8, 2004   
13     B0000SX2UC                     brittho       4     August 17, 2004   
14     B0009N5L7K               Marcel Thomas       1       March 5, 2016   
15     B0009N5L7K                  William B.       4    February 9, 2006   
16     B0009N5L7K               K. Mcilhargey       5    February 7, 2006   
17     B0009N5L7K              Stephen Cahill       1   December 20, 2016   
18     B0009N5L7K                       Mihir       5   December 13, 2009   
19     B0009N5L7K                   L. Hughes       1       July 21, 2005   
20     B0009N5L7K          1 Stop 4 Whats HOT       5       June 27, 2009   
21     B000SKTZ0S                      Thomas       4  September 17, 2010   
22     B000SKTZ0S           Kei, San Jose, CA       1        May 13, 2017   
23     B000SKTZ0S                      Kristy       1      March 13, 2019   
24     B000SKTZ0S               MARIO GAUTIER       5         May 1, 2017   
25     B000SKTZ0S                      R-Dash       3   February 10, 2009   
26     B000SKTZ0S              John R. Risden       4    January 19, 2011   
27     B000SKTZ0S             Amazon Customer       1    February 3, 2017   
28     B000SKTZ0S                    New York       5        May 23, 2013   
29     B000SKTZ0S                      kalani       3       July 22, 2014   
...           ...                         ...     ...                 ...   
67956  B081H6STQQ           Dr. Stuart Gitlow       3       July 23, 2019   
67957  B081H6STQQ                    Samantha       4      August 1, 2019   
67958  B081H6STQQ                        Jeff       5       July 17, 2019   
67959  B081H6STQQ                  texascutie       4      August 5, 2019   
67960  B081H6STQQ                      DebraJ       3       July 21, 2019   
67961  B081H6STQQ              Trina Burchett       4  September 22, 2019   
67962  B081H6STQQ                 PartyOfFive       4     August 20, 2019   
67963  B081H6STQQ                          MR       3     August 11, 2019   
67964  B081H6STQQ                     Tyler K       5       July 30, 2019   
67965  B081H6STQQ                       Bob H       3     October 4, 2019   
67966  B081H6STQQ                    enubrius       5     August 20, 2019   
67967  B081H6STQQ               Jerry Helsing       5   December 15, 2019   
67968  B081H6STQQ                  Jixue Yang       5    October 20, 2019   
67969  B081H6STQQ                   Aditya A.       5     August 23, 2019   
67970  B081H6STQQ                  SoundFreak       1       July 23, 2019   
67971  B081H6STQQ                    Bialynia       5       July 14, 2019   
67972  B081H6STQQ                     Aucifer       5       July 17, 2019   
67973  B081H6STQQ                    Gclancer       5     August 14, 2019   
67974  B081H6STQQ                      Pierre       3     October 3, 2019   
67975  B081H6STQQ                      thomas       5    October 15, 2019   
67976  B0

In [10]:
ds.drop(columns=['asin', 'name' , 'date' , 'verified' , 'helpfulVotes' ] , inplace = True)

In [11]:
ds

rating                                              title  \
0           3                        Def not best, but not worst   
1           1                        Text Messaging Doesn't Work   
2           5                                    Love This Phone   
3           3                            Love the Phone, BUT...!   
4           4       Great phone service and options, lousy case!   
5           4                                Worked great for me   
6           5                Wanna cool Nokia? You have it here!   
7           4               Problem with 3588i universal headset   
8           5                                 cool phone!!!!!!!!   
9           3                            Pissed off-a little bit   
10          4                    works great, but don't dropt it   
11          1       Slow, annoying, fragile, heavy, and bulky...   
12          2              Worth paying more for something else.   
13          4             Great free phone for Sprint customers.   
14          1                                       Stupid phone   
15          4                                   Exellent Service   
16          5                                          I love it   
17          1                                      Phones locked   
18          5                                  Excellent product   
19          1                                            WARNING   
20          5                                 NEXTEL BOOST PHONE   
21          4                                          Nice, but   
22          1  It seems it doesn't work with the existing AT&...   
23          1                                  Supply are needed   
24          5                                         Five Stars   
25          3                                       does the job   
26          4                               Awesome with a But!!   
27          1                                           One Star   
28          5                            Is cheap but ok quality   
29          3                                        Three Stars   
...       ...                                                ...   
67956       3   A beautiful screen with a sub par phone attached   
67957       4  Sony could be on their way to having a flagshi...   
67958       5  Phenomenal Display that is second to none, inc...   
67959       4                                        Solid phone   
67960       3  Sony Xperia 1 J8170 GREAT PHONE! will not Blue...   
67961       4                                More Pros Than Cons   
67962       4                                 Excellent graphics   
67963       3                                        Super buggy   
67964       5                                   Huge improvement   
67965       3                          Great Concept Except ....   
67966       5                                    Get the picture   
67967       5                                      Amazing phone   
67968       5                                Forget about iPhone   
67969       5                                        Amazing !!!   
67970       1  DO NOT BUY ( Especially if using TMobile ) !!!...   
67971       5                               Great phone (for me)   
67972       5                        Best Screen on a phone 2019   
67973       5                           Much improved Sony phone   
67974       3                                  I'm not impressed   
67975       5                                        Great phone   
67976       5                                            Love it   
67977       5                                      that it works   
67978       5                           Candy bar phone is back!   
67979       3                                     Updated review   
67980       5               From iPhone to Android and loving it   
67981       5  Awesome Phone, but finger scanner is a big mis...   
67982       5                                    Simply Amazing

In [12]:
ds['sentiment'] = ds['rating'].apply(lambda rating : +1 if rating > 3 else 0)

In [13]:
ds.isnull().sum()

rating        0
title        14
body         21
sentiment     0
dtype: int64

In [14]:
ds["title"].fillna(ds["title"].mode()[0] , inplace = True)

In [15]:
ds["body"].fillna(ds["body"].mode()[0] , inplace = True)

In [16]:
ds.isnull().sum()

rating       0
title        0
body         0
sentiment    0
dtype: int64

In [17]:
#regular expressions to replace special charecters
import re
import nltk
nltk.download("stopwords") # for is then that or , is here where
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to C:\Users\Vijay Kumar
[nltk_data]     Damodar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [18]:
ps = PorterStemmer()
data = []

In [19]:
for i in range(0,67986):
    review = ds["title"][i]
    review = re.sub('[^a-zA-Z]', ' ',review)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    data.append(review)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
import joblib
cv = CountVectorizer(max_features = 3000)
x = cv.fit_transform(data).toarray()
with open('CountVectorizer','wb') as file:
    joblib.dump(cv,file)

In [15]:
y = ds.iloc[:,3:4].values

In [16]:
y

array([[0],
       [0],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 0,test_size = 0.2)

In [19]:
x_train.shape

(54388, 3000)

In [20]:
x_test.shape

(13598, 3000)

In [21]:
y_train.shape

(54388, 1)

In [23]:
y_test.shape

(13598, 1)

In [24]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(units = 3000 ,init = "random_uniform",activation = "relu"))
model.add(Dense(units = 4500 ,init = "random_uniform",activation = "relu"))

Using TensorFlow backend.
C:\Users\Vijay Kumar Damodar\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3000, activation="relu", kernel_initializer="random_uniform")`
  after removing the cwd from sys.path.
C:\Users\Vijay Kumar Damodar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=4500, activation="relu", kernel_initializer="random_uniform")`
  """


In [25]:
model.add(Dense(units = 1 ,init = "random_uniform",activation = "sigmoid"))
model.compile(optimizer = "adam",loss = "binary_crossentropy",metrics = ["accuracy"])
model.fit(x_train,y_train,epochs  = 2)

C:\Users\Vijay Kumar Damodar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


Epoch 1/2
54388/54388 [==============================] - 1582s 29ms/step - loss: 0.3436 - accuracy: 0.8502
Epoch 2/2
54388/54388 [==============================] - 1138s 21ms/step - loss: 0.2669 - accuracy: 0.8899


In [26]:
joblib.dump(model,"nlp.h5")

['nlp.h5']

In [27]:
text =  "Hello, I have this phone and used it until I decided to buy a flip phone. I have had NO problems with the battery or new cases--it has a new fish case on "
text = re.sub('[^a-zA-Z]', ' ',text)
text = text.lower()
text = text.split()
text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text = ' '.join(text)

In [28]:
y_p1 = model.predict(cv.transform([text]))

In [29]:
y_p1

array([[0.07031152]], dtype=float32)

In [30]:
y_p1 > 0.509572

array([[False]])

In [31]:
y_p1 < 0.5

array([[ True]])